name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 다운로드
        uses: actions/checkout@v4

      - name: Java 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 설치
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'

      - name: Gradle Wrapper 생성
        run: gradle wrapper --gradle-version 8.2

      - name: 실행 권한 부여
        run: chmod +x gradlew

      - name: APK 빌드
        run: ./gradlew assembleDebug --no-daemon

      - name: ✅ APK 업로드
        uses: actions/upload-artifact@v4
        with:
          name: 사육관리표-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
